import Head from 'next/head'
import React from 'react'
import styled from 'styled-components';
import { MdPlayArrow } from 'react-icons/md';
import { FaVrCardboard } from 'react-icons/fa';
import NextLink from 'next/link';

const Layout = ({ children }) => {
    return (
        <VStack>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Plan>

                <NextLink href='/'>
                    <LinkFlex>Home </LinkFlex>
                </NextLink>
                <NextLink href='/viewer'>
                    <LinkFlex>Viewer  </LinkFlex>
                </NextLink>

            </Plan>
            <VrButton>
                <FaVrCardboard />
            </VrButton>
            {children}
            <Footer>
                <Arrows>
                    <Flex>
                        <MdPlayArrow style={{ transform: 'rotate(-90deg)' }} />
                    </Flex>
                    <FlexMiddle>
                        <MdPlayArrow style={{ transform: 'rotate(180deg)' }} />
                        <MdPlayArrow />
                    </FlexMiddle>
                    <Flex>
                        <MdPlayArrow style={{ transform: 'rotate(90deg)' }} />
                    </Flex>
                </Arrows>
            </Footer>
        </VStack>
    )
}


const Plan = styled.div`
 position:absolute;
 bottom:0;
 left:0;
 bottom:0;
 z-index:1;
 margin:30px; 
`;

const LinkFlex = styled.div`
 
 
`;

const VrButton = styled.div`
 position:absolute;
 top:0;
 right:0; 
 z-index:1;
 margin:30px;
`;

const Footer = styled.footer`
 position:absolute;
 right:0;
 bottom:0;
 z-index:1;
`;

const Text = styled.h1`
 
`;

const FlexMiddle = styled.div`
 display:flex;
 justify-content:space-between;
 width:50px;
 z-index:1;
`;

const Flex = styled.div`
 display:flex;
 justify-content:center;
 width:100%;
 z-index:1;
`;

const Arrows = styled.div`
 display:flex;
 flex-direction:column;
 justify-content:center;
 align-items:center;
 z-index:1;
 margin:30px;
`;

const VStack = styled.div` 
  position:relative;
  height:100vh;
  width:100vw;
`;

export default Layout